"""Default values for settings

Revision ID: 231a1345d050
Revises: 6946a77ecb48
Create Date: 2018-07-15 09:47:29.109783+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231a1345d050'
down_revision = '6946a77ecb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
