"""Allow/Deny bots setting for groups

Revision ID: 6946a77ecb48
Revises: be807866d0c8
Create Date: 2018-07-15 09:40:11.977185+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6946a77ecb48'
down_revision = 'be807866d0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('allow_bots', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'allow_bots')
    # ### end Alembic commands ###
