"""Auctionable Field

Revision ID: 8a524959db9e
Revises: ed4ffe9ef18e
Create Date: 2018-09-11 19:34:09.084320+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a524959db9e'
down_revision = 'ed4ffe9ef18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('auctionable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'auctionable')
    # ### end Alembic commands ###
