"""Adjust ItemType

Revision ID: 9999bfbc8326
Revises: 9a140c75c676
Create Date: 2018-09-25 19:40:04.492148+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9999bfbc8326'
down_revision = '9a140c75c676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', sa.Column('item_type', sa.Enum('UNKNOWN', 'RES', 'ALCH', 'OTHER', 'MISC', 'IGNORE', name='itemtype'),
                                    nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
