"""Added ItemType

Revision ID: 9a140c75c676
Revises: ada072ff50ad
Create Date: 2018-09-25 18:49:49.342418+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a140c75c676'
down_revision = 'ada072ff50ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_type', sa.Enum('UNKNOWN', 'RES', 'ALCH', 'OTHER', 'MISC', name='itemtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_type')
    # ### end Alembic commands ###
