"""Added constraint

Revision ID: ada072ff50ad
Revises: 90307478638b
Create Date: 2018-09-21 19:33:00.157166+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada072ff50ad'
down_revision = '90307478638b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_usr_item', 'user_auction_watchlist', ['user_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_usr_item', 'user_auction_watchlist', type_='unique')
    # ### end Alembic commands ###
