"""Default for weight

Revision ID: c155210e0835
Revises: 9999bfbc8326
Create Date: 2018-09-25 20:23:39.807298+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c155210e0835'
down_revision = '9999bfbc8326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
