"""Guild Stock

Revision ID: eba443f4124a
Revises: f51c741daec1
Create Date: 2018-09-29 17:35:43.363740+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eba443f4124a'
down_revision = 'f51c741daec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('stock', sa.UnicodeText(length=2500), nullable=True),
    sa.Column('date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('stock_type', sa.Enum('RES', 'ALCH', 'OTHER', 'MISC', name='guildstocktype'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_stock')
    # ### end Alembic commands ###
