"""Default for weight... Pt. 2

Revision ID: f51c741daec1
Revises: c155210e0835
Create Date: 2018-09-25 20:34:47.384730+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51c741daec1'
down_revision = 'c155210e0835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', sa.Column('weight', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
