CC_SET_WELCOME = 'Welcome:'
CC_HELP = 'Help'
CC_SQUAD = 'Squad'
CC_SHOW_WELCOME = 'Show welcome message'
CC_TURN_ON_WELCOME = 'Turn on welcome message'
CC_TURN_OFF_WELCOME = 'Turn off welcome message'
CC_SET_TRIGGER = 'Set trigger:'
CC_UNSET_TRIGGER = 'Unset trigger:'
CC_TRIGGER_LIST = 'Trigger list'
CC_ADMIN_LIST = 'Admin list'
CC_PING = 'Ping'
CC_DAY_STATISTICS = 'Daily statistics'
CC_WEEK_STATISTICS = 'Weekly statistics'
CC_BATTLE_STATISTICS = 'Battle statistics'
CC_ALLOW_TRIGGER_ALL = 'allow everyone to trigger '
CC_DISALLOW_TRIGGER_ALL = 'prevent everyone from triggering'
CC_ADMINS = ['admins', 'commander']
CC_ALLOW_PIN_ALL = 'allow everyone to pin'
CC_DISALLOW_PIN_ALL = 'prevent everyone from pinning'
CC_BOSS_1 = ['бандит', 'краб']
CC_BOSS_2 = ['жало', 'королева роя']
CC_BOSS_3 = ['циклоп', 'борода']
CC_BOSS_4 = ['гидра', 'лич']
CC_OPEN_HIRING = 'Open admissions'
CC_CLOSE_HIRING = 'Close admissions'
CC_PIN = 'Pin'
CC_SILENT_PIN = 'Unpin'
CC_DELETE = 'Delete'
CC_KICK = 'Kick'
