CC_SET_WELCOME = 'welcome:'
CC_HELP = 'help'
CC_SQUAD = 'squad'
CC_SHOW_WELCOME = 'show welcome message'
CC_TURN_ON_WELCOME = 'turn on welcome message'
CC_TURN_OFF_WELCOME = 'turn off welcome message'
CC_SET_TRIGGER = 'trigger:'
CC_UNSET_TRIGGER = 'untrigger:'
CC_TRIGGER_LIST = 'trigger list'
CC_ADMIN_LIST = 'admin list'
CC_PING = 'ping'
CC_DAY_STATISTICS = 'daily stats'
CC_WEEK_STATISTICS = 'weekly stats'
CC_BATTLE_STATISTICS = 'battle stats'
CC_ALLOW_TRIGGER_ALL = 'allow everyone to trigger'
CC_DISALLOW_TRIGGER_ALL = 'prevent everyone from triggering'
CC_ADMINS = ['admins', 'commander']
CC_ALLOW_PIN_ALL = 'allow everyone to pin'
CC_DISALLOW_PIN_ALL = 'prevent everyone from pinning'
CC_BOSS_1 = ['бандит', 'краб']
CC_BOSS_2 = ['жало', 'королева роя']
CC_BOSS_3 = ['циклоп', 'борода']
CC_BOSS_4 = ['гидра', 'лич']
CC_OPEN_HIRING = 'open admissions'
CC_CLOSE_HIRING = 'close admissions'
CC_PIN = 'pin'
CC_SILENT_PIN = 'unpin'
CC_DELETE = 'delete'
CC_KICK = 'kick'
