CC_SET_WELCOME = 'приветствие:'
CC_HELP = 'помощь'
CC_SQUAD = 'отряд'
CC_SHOW_WELCOME = 'покажи приветствие'
CC_TURN_ON_WELCOME = 'включи приветствие'
CC_TURN_OFF_WELCOME = 'выключи приветствие'
CC_SET_TRIGGER = 'затриггерь:'
CC_UNSET_TRIGGER = 'разтриггерь:'
CC_TRIGGER_LIST = 'список триггеров'
CC_ADMIN_LIST = 'список админов'
CC_PING = 'пинг'
CC_DAY_STATISTICS = 'статистика за день'
CC_WEEK_STATISTICS = 'статистика за неделю'
CC_BATTLE_STATISTICS = 'статистика за бой'
CC_ALLOW_TRIGGER_ALL = 'разрешить триггерить всем'
CC_DISALLOW_TRIGGER_ALL = 'запретить триггерить всем'
CC_ADMINS = ['админы', 'офицер']
CC_ALLOW_PIN_ALL = 'пинят все'
CC_DISALLOW_PIN_ALL = 'хорош пинить'
CC_BOSS_1 = ['бандит', 'краб']
CC_BOSS_2 = ['жало', 'королева роя']
CC_BOSS_3 = ['циклоп', 'борода']
CC_BOSS_4 = ['гидра', 'лич']
CC_OPEN_HIRING = 'открыть набор'
CC_CLOSE_HIRING = 'закрыть набор'
CC_PIN = 'пин'
CC_SILENT_PIN = 'спин'
CC_DELETE = 'удоли'
CC_KICK = 'свали'
