ADMIN_COMMAND_ORDER = '⚔Orders'
ADMIN_COMMAND_STATUS = '🔎Status'
ADMIN_COMMAND_GROUPS = '👥Groups'
ADMIN_COMMAND_RECRUIT = '📬Squad Requests'
ADMIN_COMMAND_FIRE_UP = '⛏Harvest'
ADMIN_COMMAND_SQUAD_LIST = '🗂Squad List'
ADMIN_COMMAND_ADMINPANEL = '🦅Admin Panel🦅'
ADMIN_COMMAND_REPORTS = '📜Reports'
ADMIN_COMMAND_ATTENDANCE = '⛳️Attendance'

USER_COMMAND_ME = '🏅Hero'
USER_COMMAND_TOP = '🌟Top'
USER_COMMAND_SQUAD = '⚜Squad'
USER_COMMAND_STATISTICS = '📊Statistics'
USER_COMMAND_BUILD = '🚧Coming Soon'
USER_COMMAND_CONTACTS = '💬Chat'
USER_COMMAND_SQUAD_REQUEST = '⚜Join Squad'
USER_COMMAND_SQUAD_LEAVE = '☄Leave Squad'

USER_COMMAND_BACK = '🔙Go Back'

TOP_COMMAND_ATTACK = '⚔'
TOP_COMMAND_DEFENCE = '🛡'
TOP_COMMAND_EXP = '🔥'
TOP_COMMAND_BUILD = '👷🏻'

TOP_COMMAND_BATTLES = '⛳️'

STATISTICS_COMMAND_EXP = '🔥XP'
