ADMIN_COMMAND_ORDER = 'Приказы'
ADMIN_COMMAND_STATUS = 'Статус'
ADMIN_COMMAND_GROUPS = 'Группы'
ADMIN_COMMAND_RECRUIT = 'Заявки в отряд'
ADMIN_COMMAND_FIRE_UP = 'Чистка отряда'
ADMIN_COMMAND_SQUAD_LIST = 'Список отряда'
ADMIN_COMMAND_ADMINPANEL = '/admin'

USER_COMMAND_ME = 'Герой'
USER_COMMAND_TOP = 'Топ'
USER_COMMAND_SQUAD = 'Отряд'
USER_COMMAND_STATISTICS = 'Статистика'
USER_COMMAND_BUILD = 'Стройка'
USER_COMMAND_CONTACTS = 'Связь'
USER_COMMAND_SQUAD_REQUEST = 'Хочу в отряд'

USER_COMMAND_BACK = '🔙Назад'
