ITEMS = {"Stinky Sumac": "39",
         "Mercy Sassafras": "40",
         "Cliff Rue": "41",
         "Love Creeper": "42",
         "Wolf Root": "43",
         "Swamp Lavender": "44",
         "White Blossom": "45",
         "Ilaves": "46",
         "Ephijora": "47",
         "Storm Hyssop": "48",
         "Cave Garlic": "49",
         "Yellow Seed": "50",
         "Tecceagrass": "51",
         "Spring Bay Leaf": "52",
         "Ash Rosemary": "53",
         "Sanguine Parsley": "54",
         "Sun Tarragon": "55",
         "Maccunut": "56",
         "Dragon Seed": "57",
         "Queen's Pepper": "58",
         "Plasma Of Abyss": "59",
         "Ultramarine Dust": "60",
         "Ethereal Bone": "61",
         "Itacory": "62",
         "Assassin Vine": "63",
         "Kloliarway": "64"
         }
